# Use Node LTS
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the code
COPY . .

# Build NestJS
RUN npm run build

# Expose app port
EXPOSE 3000

# Run the app
CMD ["node", "dist/main"]
